version: "3.9"

services:
  bot:
    container_name: almanax_discord
    build: ./src/
    volumes:
      - ./src/:/usr/src/app/
    env_file: 
      - prod.env
    environment: 
      - TZ=Europe/Paris
    restart: always